spring:
  application:
    name: greenhousedigitaltwin

  datasource:
    url: jdbc:postgresql://localhost:5432/greenhouse_digital_twin
    username: greenhouse
    password: greenhouse

  jpa:
    hibernate:ddl-auto: none
    open-in-view: false



#  Configure it later
#  integration:
#    mqtt:
#      broker-url: tcp://localhost:1883
#      client-id: greenhouse-digital-twin-backend