spring:
  application:
    name: greenhousedigitaltwin

  datasource:
    url: jdbc:postgresql://localhost:5432/greenhouse_digital_twin
    username: greenhouse
    password: greenhouse

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true

